# Generated by Django 6.0 on 2026-03-13 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_number', models.CharField(default='573001234567', max_length=20, verbose_name='Número de WhatsApp')),
                ('business_hours', models.CharField(default='Lun-Sáb 8:00-18:00 · Dom 8:00-13:00', max_length=200, verbose_name='Horarios de atención')),
                ('facebook_url', models.URLField(default='https://facebook.com/tu_pagina', verbose_name='URL de Facebook')),
                ('instagram_url', models.URLField(default='https://instagram.com/tu_perfil', verbose_name='URL de Instagram')),
                ('welcome_message', models.TextField(default='¡Hola! Bienvenido a CAMPOVERDE. ¿En qué podemos ayudarte?', verbose_name='Mensaje de bienvenida')),
                ('order_wa_prefix', models.CharField(default='Pedido CAMPOVERDE', max_length=100, verbose_name='Prefijo de pedido WhatsApp')),
            ],
            options={
                'verbose_name': 'Configuración del Sitio',
                'verbose_name_plural': 'Configuraciones del Sitio',
            },
        ),
    ]
