# Generated by Django 6.0 on 2026-03-13 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='order_wa_prefix',
            field=models.CharField(default='Hola, quiero hacer este pedido', max_length=100, verbose_name='Prefijo de pedido WhatsApp'),
        ),
    ]
