# Generated by Django 6.0 on 2026-03-15 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_siteconfiguration_order_wa_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='order_wa_prefix',
            field=models.CharField(default='Hola!, quiero hacer este pedido de Manjares del Campo', max_length=100, verbose_name='Prefijo de pedido WhatsApp'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='welcome_message',
            field=models.TextField(default='¡Hola! Bienvenido a MANJARES DEL CAMPO. ¿En qué podemos ayudarte?', verbose_name='Mensaje de bienvenida'),
        ),
    ]
