# Generated by Django 6.0 on 2026-03-15 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_siteconfiguration_order_wa_prefix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='default_shipping_cost',
            field=models.IntegerField(default=10000, verbose_name='Costo de envío base'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='free_shipping_threshold',
            field=models.IntegerField(default=100000, verbose_name='Umbral de envío gratis'),
        ),
    ]
