# Generated by Django 6.0 on 2026-03-15 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Nuevo pedido'), ('confirmed', 'Confirmado'), ('preparing', 'En preparación'), ('sent', 'Enviado'), ('delivered', 'Entregado')], default='pending', max_length=20),
        ),
    ]
