# Generated by Django 6.0 on 2026-03-08 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_min_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='🥦', help_text='Emoji o nombre de icono', max_length=20),
        ),
    ]
