# Generated by Django 6.0 on 2026-03-13 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_options_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogramo'), ('libra', 'Libra'), ('unidad', 'Unidad'), ('combo', 'Combo')], default='unidad', max_length=20),
        ),
    ]
