# Generated by Django 6.0 on 2026-03-15 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_on_offer',
            field=models.BooleanField(default=False, verbose_name='¿Está en oferta?'),
        ),
        migrations.AddField(
            model_name='product',
            name='offer_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio de oferta'),
        ),
    ]
