# Generated by Django 6.0 on 2026-03-15 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, default='🥦', help_text='Emoji o clase de Bootstrap (bi-...)', max_length=50),
        ),
    ]
